version: '3'

services:
  database-dashboard:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dashboard
      - MYSQL_DATABASE=dashboard
      - MYSQL_USER=dashboard
      - MYSQL_PASSWORD=dashboard
    volumes:
      - mysql_dashboard:/var/lib/mysql

  php:
    build:
      context: ./docker/php-fpm
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - database-dashboard
    volumes:
      - .:/var/www
      - ${HOME}/.composer:/.composer
    environment:
      - "COMPOSER_MEMORY_LIMIT=-1"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    ports:
      - ${HTTP_PORT-80}:80
      - ${HTTPS_PORT-443}:443
    depends_on:
      - php

volumes:
  mysql_dashboard: {}